In [1]:
import pandas as pd
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
from sklearn.svm import SVC

In [2]:
df=pd.read_csv('loan_data.csv')

In [3]:
df

       person_age person_gender  ... previous_loan_defaults_on_file  loan_status
0            22.0        female  ...                             No            1
1            21.0        female  ...                            Yes            0
2            25.0        female  ...                             No            1
3            23.0        female  ...                             No            1
4            24.0          male  ...                             No            1
...           ...           ...  ...                            ...          ...
44995        27.0          male  ...                             No            1
44996        37.0        female  ...                             No            1
44997        33.0          male  ...                             No            1
44998        29.0          male  ...                             No            1
44999        24.0          male  ...                             No            1

[45000 rows x 14 columns]

In [4]:
x = df.drop(columns='loan_status')
y = df.loan_status

In [5]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, random_state=42, train_size=0.8)

In [6]:
# num_col = x.select_dtypes(include = 'number').columns
obj_col = x.select_dtypes(include = 'object').columns

In [7]:
x[obj_col].nunique()

person_gender                     2
person_education                  5
person_home_ownership             4
loan_intent                       6
previous_loan_defaults_on_file    2
dtype: int64

In [8]:
x['person_education'].unique()

array(['Master', 'High School', 'Bachelor', 'Associate', 'Doctorate'],
      dtype=object)

In [9]:
order = ['Master', 'High School', 'Bachelor', 'Associate', 'Doctorate']

In [10]:
preprocessing  = ColumnTransformer(
    transformers = [
        ('onehot_encodedr', OneHotEncoder(handle_unknown='ignore'), obj_col.drop('person_education')),
        ('orndinal_encoder', OrdinalEncoder(categories=[order], handle_unknown='use_encoded_value', unknown_value=-1), ['person_education'])

    ], remainder= 'passthrough'
)

main_pipeline = Pipeline(
    steps=[
        ('preprocessing', preprocessing),
        ('model', SVC(random_state=42))
    ]
)

grid_search_cv = GridSearchCV(
    estimator = main_pipeline,
    kernal={
        'model__criterion' : ['gini', 'entropy'],           
        'model__min_samples_split' : [2, 5, 7, 10],
        'model__min_samples_leaf' : [1, 3, 5, 7, 10],
        'model__splitter' : ['best', 'random']
    }, verbose = 10, n_jobs = -1
)

grid_search_cv.fit(xtrain, ytrain)

TypeError: GridSearchCV.__init__() got an unexpected keyword argument 'kernal'

 if we are using any algorithm then there is no need to use that model name but if we are using pipeline then we have to use model name along with double underscore
e.g., model__parameter

In [ ]:
grid_search_cv.best_estimator_

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehot_encodedr',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['person_gender', 'person_home_ownership', 'loan_intent',
       'previous_loan_defaults_on_file'],
      dtype='object')),
                                                 ('orndinal_encoder',
                                                  OrdinalEncoder(categories=[['Master',
                                                                              'High '
                                                                              'School',
                                                                              'Bachelor',
                                                                              'Associate',
                                                                              'Doctorate']],
                                                                 handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['person_education'])])),
                ('model',
                 DecisionTreeClassifier(criterion='entropy', max_depth=20,
                                        min_samples_leaf=10,
                                        random_state=42))])

In [ ]:
grid_search_cv.best_params_

{'model__criterion': 'entropy',
 'model__max_depth': 20,
 'model__min_samples_leaf': 10,
 'model__min_samples_split': 2,
 'model__splitter': 'best'}

In [ ]:
grid_search_cv.cv_results_

{'mean_fit_time': array([0.40701299, 0.1784955 , 0.38342366, 0.17366505, 0.36153522,
        0.16847849, 0.35575862, 0.15776482, 0.34637327, 0.16058426,
        0.34450169, 0.1685462 , 0.35215263, 0.16504211, 0.34127235,
        0.16264215, 0.34793739, 0.15915008, 0.34733725, 0.15710764,
        0.35235481, 0.15944934, 0.34076433, 0.15539474, 0.32818174,
        0.153824  , 0.33816895, 0.15361743, 0.32778511, 0.16195202,
        0.33544297, 0.16394219, 0.33708119, 0.15642996, 0.37343612,
        0.1732224 , 0.41135283, 0.17093205, 0.3279644 , 0.15651622,
        0.1934278 , 0.11888232, 0.19994717, 0.12713852, 0.19475169,
        0.12503486, 0.21519227, 0.12760892, 0.18888731, 0.12295985,
        0.18335681, 0.12832232, 0.19540267, 0.13587413, 0.19485426,
        0.10896344, 0.18542061, 0.12581997, 0.19289536, 0.11047449,
        0.19479179, 0.11958923, 0.17732654, 0.12072206, 0.18831449,
        0.11794615, 0.18455038, 0.13097801, 0.20128646, 0.12163997,
        0.18908792, 0.10372815, 0.18297505, 0.13086271, 0.20222931,
        0.12508411, 0.18617654, 0.10651989, 0.18828754, 0.11567116,
        0.35918741, 0.16916676, 0.34310055, 0.17168403, 0.35189734,
        0.17709336, 0.35645075, 0.16622052, 0.34849086, 0.15871439,
        0.35336523, 0.15130687, 0.35295997, 0.16795197, 0.33118043,
        0.14903951, 0.38717194, 0.15680847, 0.41764512, 0.1720675 ,
        0.33541999, 0.1598484 , 0.38559489, 0.1955936 , 0.3267004 ,
        0.15888548, 0.3498158 , 0.15321035, 0.33393483, 0.1585515 ,
        0.33219128, 0.16434975, 0.32343659, 0.14776802, 0.31715522,
        0.15372009, 0.32770066, 0.14925613, 0.32875681, 0.16241875,
        0.3674067 , 0.18304386, 0.38686481, 0.17291002, 0.37226224,
        0.16812606, 0.39946232, 0.17002382, 0.4928092 , 0.2326714 ,
        0.55806136, 0.2690001 , 0.47997413, 0.23606935, 0.4000155 ,
        0.17310834, 0.37052422, 0.16607828, 0.41563449, 0.24119401,
        0.5074017 , 0.22080779, 0.49856353, 0.2011435 , 0.44477921,
        0.22913461, 0.39473619, 0.1702291 , 0.40162129, 0.2043735 ,
        0.42868204, 0.21140509, 0.34385285, 0.16388173, 0.33826728,
        0.15901604, 0.34479437, 0.15931587, 0.33673382, 0.16784306,
        0.37231159, 0.18731093, 0.37899532, 0.17088795, 0.38479185,
        0.16688085, 0.36072383, 0.15540733, 0.36144986, 0.16695762,
        0.33827929, 0.16561947, 0.35245237, 0.17489133, 0.34357357,
        0.16818705, 0.35677867, 0.17266822, 0.32648926, 0.16236577,
        0.36123986, 0.16188517, 0.33912573, 0.16765642, 0.33992934,
        0.15825796, 0.33874817, 0.15897803, 0.34168305, 0.15844741,
        0.34067464, 0.15146184, 0.33259993, 0.15439529, 0.32943764,
        0.15851502, 0.3885664 , 0.19475198, 0.34361086, 0.15565424,
        0.43801675, 0.1765955 , 0.4289361 , 0.17317486, 0.43915501,
        0.17058105, 0.4290473 , 0.1575695 , 0.42765446, 0.16168671,
        0.42073245, 0.17200856, 0.42014065, 0.1674212 , 0.40810294,
        0.1710535 , 0.4057086 , 0.17685137, 0.4109066 , 0.1610261 ,
        0.40516434, 0.16839528, 0.40694051, 0.18041368, 0.39959807,
        0.16042285, 0.40383019, 0.15864854, 0.41727486, 0.16330271,
        0.38581414, 0.16257334, 0.38854737, 0.17406387, 0.40885677,
        0.17409067, 0.39040427, 0.1639596 , 0.38219075, 0.16391435,
        0.2337007 , 0.124401  , 0.21973553, 0.12429886, 0.22401199,
        0.12567596, 0.21375632, 0.11539216, 0.20195341, 0.12114601,
        0.20927744, 0.10965037, 0.27612939, 0.1781878 , 0.22560573,
        0.12366705, 0.20906458, 0.11449461, 0.20563221, 0.11546278,
        0.20514512, 0.12334018, 0.2076683 , 0.1192997 , 0.20608544,
        0.11948652, 0.2105576 , 0.11899014, 0.23419795, 0.12775016,
        0.21447906, 0.10905857, 0.20815897, 0.12537327, 0.21155572,
        0.12067327, 0.2062531 , 0.1194407 , 0.22204595, 0.12117791,
        0.4129591 , 0.15501909, 0.41457705, 0.16519299, 0.39938307,
        0.15705843, 0.40165443, 0.16731625, 0.39644527, 0.1644176 ,
        0.39585361, 0.16945786, 0.39951334, 0.16640992, 0.39975843,
        0.16402607, 0.39895921, 0.1743289 , 0.40798035, 0.15655975,
        0.39201417, 0.17577186, 0.38939066, 0.16551194, 0.39612503,
        0.1612184 , 0.398629  , 0.15834088, 0.39534893, 0.1557591 ,
        0.37976775, 0.16199946, 0.38279305, 0.14696679, 0.37765927,
        0.14915915, 0.44877954, 0.19915719, 0.35979047, 0.16125975,
        0.42938132, 0.18282499, 0.42542725, 0.17497807, 0.43203492,
        0.17624378, 0.45075102, 0.18159881, 0.39845533, 0.17144318,
        0.43189139, 0.16214957, 0.45301013, 0.19339042, 0.43957605,
        0.16237273, 0.42809687, 0.15608764, 0.40794153, 0.16898441,
        0.42966275, 0.16818452, 0.39921131, 0.15858159, 0.41170998,
        0.16442499, 0.41236143, 0.161766  , 0.40316133, 0.1594501 ,
        0.40587258, 0.15297318, 0.40920234, 0.15602794, 0.39289207,
        0.15713258, 0.37958646, 0.16136336, 0.38198242, 0.15670419,
        0.45721369, 0.1854342 , 0.41671743, 0.18442202, 0.426998  ,
        0.16984882, 0.4389257 , 0.17273264, 0.43258247, 0.1584456 ,
        0.42740526, 0.17035332, 0.44407272, 0.16274824, 0.4468411 ,
        0.16213331, 0.42697735, 0.14906693, 0.42712669, 0.16667376,
        0.40380354, 0.16387939, 0.40733366, 0.16620426, 0.3763257 ,
        0.15893559, 0.38634658, 0.15019307, 0.3818337 , 0.1646462 ,
        0.38141494, 0.14507308, 0.38506918, 0.14531174, 0.38498273,
        0.15960665, 0.37540751, 0.15326219, 0.33142033, 0.13477325]),
 'std_fit_time': array([0.03278493, 0.0208598 , 0.0356397 , 0.02230923, 0.01114389,
        0.01317208, 0.01320951, 0.01733841, 0.00980776, 0.02201483,
        0.02106386, 0.01689861, 0.01979571, 0.01879055, 0.02610779,
        0.0122663 , 0.01756038, 0.01319496, 0.0214185 , 0.01344229,
        0.01414131, 0.01943367, 0.01054773, 0.01862114, 0.01137584,
        0.01595965, 0.01406868, 0.00427044, 0.01152539, 0.0196004 ,
        0.01501462, 0.01415132, 0.01778967, 0.02316361, 0.02840957,
        0.02346559, 0.0252403 , 0.02486219, 0.01700423, 0.01833923,
        0.01056899, 0.00563236, 0.022154  , 0.0128582 , 0.02054196,
        0.00675873, 0.00958267, 0.01145561, 0.00740537, 0.00698898,
        0.02147871, 0.01035446, 0.02259005, 0.01065727, 0.01424007,
        0.01421683, 0.0198526 , 0.01410903, 0.01481279, 0.01379347,
        0.01514351, 0.00830298, 0.01910131, 0.00749926, 0.01273167,
        0.00968914, 0.02251455, 0.01597568, 0.01423071, 0.01202422,
        0.01083751, 0.00486298, 0.01033804, 0.00862227, 0.01000343,
        0.01585995, 0.01852033, 0.0127693 , 0.01573948, 0.01044446,
        0.01685515, 0.01256331, 0.02283551, 0.02144114, 0.03468081,
        0.0138077 , 0.0157258 , 0.01984966, 0.01244123, 0.0185703 ,
        0.00915073, 0.02142363, 0.01948826, 0.0136426 , 0.01608102,
        0.02100873, 0.04146024, 0.00985142, 0.01542405, 0.03353598,
        0.00961751, 0.01752281, 0.00735606, 0.01713227, 0.0276536 ,
        0.01402982, 0.02449217, 0.01085002, 0.00887857, 0.01450592,
        0.01383041, 0.01177709, 0.01844664, 0.01535976, 0.01523209,
        0.01791671, 0.01705285, 0.01172837, 0.02296316, 0.01816153,
        0.01537774, 0.01750631, 0.02409045, 0.00757993, 0.01339773,
        0.0155234 , 0.03001735, 0.01338145, 0.01613741, 0.03742157,
        0.04110388, 0.02505807, 0.03604806, 0.02707289, 0.01435141,
        0.01466559, 0.02188989, 0.01204484, 0.04726059, 0.0569904 ,
        0.07125281, 0.01387448, 0.02394412, 0.01941871, 0.02462832,
        0.01652657, 0.01039843, 0.01659698, 0.01744465, 0.03707951,
        0.04243621, 0.01551199, 0.00766877, 0.00373628, 0.01151014,
        0.01163767, 0.00709418, 0.01027681, 0.01041221, 0.01423978,
        0.01337585, 0.01131553, 0.00708072, 0.0055871 , 0.00904806,
        0.0136448 , 0.02068476, 0.01551715, 0.01398337, 0.01534468,
        0.01453233, 0.01604028, 0.0211768 , 0.01386556, 0.02946103,
        0.01536949, 0.02012866, 0.01398825, 0.02494716, 0.01607276,
        0.01684924, 0.02200704, 0.01488369, 0.01474477, 0.01766227,
        0.01934449, 0.01596339, 0.01128221, 0.02503461, 0.01927024,
        0.02506362, 0.01376667, 0.01199748, 0.01112537, 0.0093587 ,
        0.00788315, 0.01377156, 0.01509942, 0.01144641, 0.00925249,
        0.01245808, 0.01771701, 0.01426958, 0.00784465, 0.01575083,
        0.02078083, 0.02092324, 0.01115472, 0.02037572, 0.02192603,
        0.02524907, 0.01777292, 0.0204846 , 0.02218772, 0.01913874,
        0.01865429, 0.01000853, 0.01680301, 0.00980407, 0.00909576,
        0.00868767, 0.00910116, 0.00804583, 0.01156547, 0.0074743 ,
        0.00676677, 0.01507932, 0.01461406, 0.02813472, 0.01235733,
        0.01182515, 0.01228016, 0.01294821, 0.01406001, 0.01101746,
        0.02045421, 0.02091009, 0.0096846 , 0.01137763, 0.02468228,
        0.0149939 , 0.0102774 , 0.01239421, 0.00978671, 0.00620992,
        0.00738415, 0.00579006, 0.01413424, 0.01893981, 0.01470168,
        0.01517053, 0.01050135, 0.04657223, 0.01195983, 0.01788741,
        0.00741589, 0.02629789, 0.01064494, 0.01018642, 0.01595431,
        0.01892333, 0.01311975, 0.02104615, 0.01903829, 0.01672616,
        0.00460577, 0.01959905, 0.01668973, 0.02739878, 0.01159038,
        0.01033231, 0.01342421, 0.01546757, 0.01505015, 0.0185567 ,
        0.01524842, 0.01879874, 0.00815031, 0.0132297 , 0.01172774,
        0.00299196, 0.01152366, 0.02528396, 0.01487813, 0.01002639,
        0.0131316 , 0.01600085, 0.01865719, 0.01650638, 0.02212114,
        0.01527764, 0.0170863 , 0.02390405, 0.01349824, 0.01702106,
        0.01186038, 0.00495528, 0.01932743, 0.02012661, 0.01773223,
        0.02084276, 0.01665707, 0.01647488, 0.00369854, 0.01234321,
        0.02363682, 0.02457737, 0.0097018 , 0.01300396, 0.01726565,
        0.0180193 , 0.01622267, 0.02142247, 0.01538155, 0.0285316 ,
        0.01570094, 0.01887576, 0.03293171, 0.02846006, 0.0158114 ,
        0.02275905, 0.02138291, 0.01773911, 0.02272274, 0.00832568,
        0.0299354 , 0.01962708, 0.03006644, 0.02719807, 0.01833157,
        0.03249185, 0.02406591, 0.01109253, 0.0186682 , 0.02369983,
        0.01708233, 0.01725357, 0.01484816, 0.02792438, 0.0232488 ,
        0.02457392, 0.01776862, 0.0179631 , 0.02161598, 0.0075112 ,
        0.02777134, 0.01862369, 0.0301683 , 0.01504824, 0.02268545,
        0.01999317, 0.02169772, 0.00901531, 0.01563979, 0.01965914,
        0.02827568, 0.05222822, 0.01999146, 0.02102185, 0.02000162,
        0.03016938, 0.02039107, 0.02878299, 0.02751781, 0.01449957,
        0.01117686, 0.02854824, 0.02215274, 0.0255013 , 0.0183458 ,
        0.02138307, 0.01560275, 0.01542825, 0.01432373, 0.01984379,
        0.02637506, 0.02280017, 0.0191176 , 0.02497771, 0.01904725,
        0.01229282, 0.01711403, 0.03124034, 0.01476149, 0.01156819,
        0.00988237, 0.01546456, 0.01550389, 0.03209266, 0.01478743,
        0.01100021, 0.01128062, 0.01300335, 0.01624931, 0.01200507,
        0.0250717 , 0.01504272, 0.02493336, 0.0223368 , 0.00715791]),
 'mean_score_time': array([0.03515797, 0.02919564, 0.02835894, 0.0307056 , 0.02980156,
        0.03104043, 0.03240008, 0.02709804, 0.02663031, 0.03340397,
        0.03135471, 0.03031192, 0.0290091 , 0.02303925, 0.03118701,
        0.02810998, 0.02645707, 0.02960095, 0.03057141, 0.02937007,
        0.02801285, 0.02870712, 0.03040767, 0.03236876, 0.02938347,
        0.02862778, 0.02644157, 0.02793264, 0.0307301 , 0.03091912,
        0.03076191, 0.03145609, 0.03173733, 0.03368464, 0.04544139,
        0.03915162, 0.03108907, 0.02520199, 0.03183045, 0.03328471,
        0.02501621, 0.02766175, 0.02810216, 0.03049145, 0.02544188,
        0.02558346, 0.02860098, 0.02836447, 0.03038254, 0.03113565,
        0.02788725, 0.02964969, 0.02766376, 0.02488055, 0.02352824,
        0.02618022, 0.03148637, 0.02816205, 0.0274446 , 0.03044815,
        0.02751236, 0.02626786, 0.02960067, 0.02811732, 0.02968707,
        0.02838378, 0.03019371, 0.02836099, 0.02850165, 0.03219995,
        0.03022084, 0.02360129, 0.029914  , 0.02644906, 0.02751017,
        0.03136153, 0.03125181, 0.02456403, 0.02838011, 0.0292273 ,
        0.0263144 , 0.02772436, 0.03069272, 0.03261161, 0.02547588,
        0.030336  , 0.02771916, 0.02792878, 0.02783389, 0.02599015,
        0.0312695 , 0.03120646, 0.03172626, 0.02734942, 0.03101239,
        0.03072572, 0.04076614, 0.02851305, 0.02799573, 0.02450566,
        0.02759042, 0.02748432, 0.02631083, 0.03635082, 0.02928529,
        0.03105903, 0.03014398, 0.03085785, 0.03104148, 0.02376876,
        0.02939854, 0.02852249, 0.03131495, 0.02709289, 0.0307982 ,
        0.03122063, 0.03156381, 0.03178592, 0.02954516, 0.03021803,
        0.03208599, 0.03143253, 0.03310685, 0.02927327, 0.03000927,
        0.02576962, 0.04791317, 0.04699349, 0.04038048, 0.04165463,
        0.04689956, 0.04175515, 0.03393822, 0.03612452, 0.03174357,
        0.04045782, 0.03024845, 0.02603168, 0.04312673, 0.04193673,
        0.04066477, 0.04492021, 0.05409837, 0.04449568, 0.03407965,
        0.03780289, 0.02685332, 0.02993479, 0.05421534, 0.03909602,
        0.03215661, 0.03193097, 0.03044472, 0.02929721, 0.03227363,
        0.03174267, 0.03041582, 0.03012309, 0.02940044, 0.02777643,
        0.03127937, 0.02938266, 0.0316925 , 0.02963095, 0.03205471,
        0.02613468, 0.0285737 , 0.02705536, 0.02584577, 0.02759752,
        0.03017321, 0.02946029, 0.02854009, 0.03000827, 0.02817569,
        0.03172746, 0.0257133 , 0.03291826, 0.03078494, 0.02712469,
        0.02927427, 0.02697725, 0.02979856, 0.03195271, 0.02769866,
        0.03061705, 0.02755394, 0.02901826, 0.02871509, 0.02689466,
        0.03157611, 0.03027205, 0.02954435, 0.0309545 , 0.02896218,
        0.02835231, 0.03275309, 0.02989759, 0.03062401, 0.02616301,
        0.03019986, 0.02846642, 0.03555126, 0.02600198, 0.02812343,
        0.02734108, 0.03063245, 0.0262609 , 0.02893376, 0.0249485 ,
        0.03091908, 0.02451887, 0.02754297, 0.02836609, 0.03070593,
        0.02845845, 0.03127475, 0.02800231, 0.0282505 , 0.03171239,
        0.02862549, 0.02649236, 0.02787485, 0.03456821, 0.03034124,
        0.02962284, 0.03031406, 0.02955694, 0.02819638, 0.03192315,
        0.02731314, 0.02745857, 0.02997479, 0.02778101, 0.03002219,
        0.02721124, 0.03025227, 0.02715998, 0.02887049, 0.0261867 ,
        0.0309309 , 0.0287499 , 0.02631931, 0.03064427, 0.02933822,
        0.02673483, 0.03117204, 0.02986836, 0.0298244 , 0.02395735,
        0.02683721, 0.02622447, 0.03951483, 0.0344255 , 0.02675252,
        0.02449064, 0.03073077, 0.02972851, 0.03244143, 0.02865148,
        0.02901011, 0.02438354, 0.02924957, 0.02842994, 0.02536736,
        0.02687273, 0.02964258, 0.02822728, 0.03845119, 0.02828636,
        0.02670689, 0.02584658, 0.03030286, 0.02831111, 0.02988424,
        0.02430916, 0.02659826, 0.02737613, 0.02969999, 0.02627716,
        0.02782807, 0.02963281, 0.02903361, 0.02825055, 0.02947025,
        0.02703362, 0.03222013, 0.02561665, 0.03152814, 0.02775564,
        0.02951198, 0.02832723, 0.02892203, 0.0280797 , 0.02695804,
        0.02807517, 0.03051639, 0.02823901, 0.03035164, 0.02450414,
        0.03106246, 0.02863226, 0.03094344, 0.0297318 , 0.02813907,
        0.02966948, 0.03155866, 0.02845244, 0.0356113 , 0.03003578,
        0.02752881, 0.02891402, 0.03231301, 0.02907476, 0.04261441,
        0.02786026, 0.02751789, 0.02763157, 0.03052387, 0.02842469,
        0.02895751, 0.0286262 , 0.03216138, 0.02632985, 0.03202043,
        0.02882342, 0.02888885, 0.02877979, 0.03080072, 0.03006482,
        0.03496408, 0.02708282, 0.03070087, 0.02779307, 0.03215685,
        0.0284791 , 0.03038473, 0.02437086, 0.03280654, 0.03281078,
        0.02958989, 0.03034401, 0.02949767, 0.02605686, 0.02990823,
        0.02827787, 0.03068242, 0.0265985 , 0.02924809, 0.02791157,
        0.03230615, 0.02445493, 0.03429861, 0.025489  , 0.03159924,
        0.02541885, 0.02998586, 0.02928104, 0.03097434, 0.02773294,
        0.03160281, 0.02974076, 0.02866921, 0.02999811, 0.03331399,
        0.02920117, 0.03025975, 0.02781105, 0.03252459, 0.02916913,
        0.03283548, 0.02794385, 0.03129153, 0.02847924, 0.0335608 ,
        0.02996516, 0.03338051, 0.03128839, 0.02814417, 0.02884741,
        0.02824068, 0.02949247, 0.03395886, 0.03172011, 0.02782974,
        0.02545929, 0.03136935, 0.02847524, 0.02728996, 0.0277164 ,
        0.03074474, 0.02554302, 0.02940683, 0.02717218, 0.02689271,
        0.02515965, 0.02900381, 0.0294744 , 0.0172924 , 0.02303028]),
 'std_score_time': array([0.00449802, 0.00319429, 0.00245435, 0.00418227, 0.00309957,
        0.00259231, 0.00703434, 0.00356746, 0.00391543, 0.00986849,
        0.0042617 , 0.00285163, 0.00324664, 0.00964912, 0.00399072,
        0.00163042, 0.006304  , 0.00495497, 0.00188244, 0.00281731,
        0.00338643, 0.00348479, 0.00148715, 0.00788696, 0.00441003,
        0.00253001, 0.00415459, 0.00341504, 0.00394762, 0.00310436,
        0.00595685, 0.00301051, 0.00511507, 0.00593502, 0.01452517,
        0.01304164, 0.00186728, 0.00379518, 0.00709851, 0.0058861 ,
        0.00800974, 0.00514996, 0.00270362, 0.00171932, 0.00629687,
        0.00451359, 0.00355057, 0.00670878, 0.00087308, 0.00518199,
        0.00249418, 0.0019148 , 0.00562012, 0.00597076, 0.00819922,
        0.00329144, 0.00320364, 0.00275986, 0.00475078, 0.01403907,
        0.00507214, 0.00598148, 0.00329643, 0.00993043, 0.00172074,
        0.00373934, 0.00293591, 0.00357304, 0.00339178, 0.00838048,
        0.00600561, 0.0047906 , 0.00490393, 0.00384057, 0.00443061,
        0.00441057, 0.00203883, 0.00283383, 0.00267034, 0.0016802 ,
        0.00234007, 0.00127716, 0.00182456, 0.0022361 , 0.00282304,
        0.0018932 , 0.00394029, 0.0044678 , 0.00427048, 0.00312667,
        0.00218887, 0.00767085, 0.00249832, 0.00245326, 0.00347006,
        0.00174062, 0.01562363, 0.00324143, 0.00314777, 0.00308354,
        0.00454562, 0.00369892, 0.00300141, 0.0097413 , 0.00324169,
        0.00304832, 0.00174999, 0.00288016, 0.00577004, 0.00313965,
        0.00251267, 0.00373889, 0.0086783 , 0.00289057, 0.0024989 ,
        0.00295365, 0.00471081, 0.00460758, 0.00435825, 0.00290599,
        0.00269768, 0.00131875, 0.00452928, 0.00325271, 0.0030757 ,
        0.00279772, 0.01118169, 0.01559723, 0.00709837, 0.00755947,
        0.01381532, 0.00634471, 0.00457867, 0.00583766, 0.00396919,
        0.00955163, 0.00661302, 0.00512137, 0.00566572, 0.00405775,
        0.00507931, 0.008401  , 0.02256728, 0.00716848, 0.00618881,
        0.00571183, 0.00372623, 0.00303382, 0.02105796, 0.00384864,
        0.00146266, 0.00274154, 0.0006514 , 0.00148505, 0.00198586,
        0.00415395, 0.00074513, 0.00504191, 0.00090217, 0.00552163,
        0.00204965, 0.00088   , 0.00151994, 0.00147931, 0.00327346,
        0.00358235, 0.00235543, 0.00309506, 0.00466232, 0.00279993,
        0.0051744 , 0.00463095, 0.00229967, 0.00137694, 0.00224494,
        0.00075691, 0.00602178, 0.00654975, 0.00524162, 0.00344194,
        0.00335961, 0.00340276, 0.00461531, 0.00237762, 0.00324778,
        0.00316793, 0.00339904, 0.0042317 , 0.00259798, 0.00263335,
        0.00357552, 0.00197293, 0.0023046 , 0.0034934 , 0.00165109,
        0.00243545, 0.00130305, 0.00377459, 0.00197952, 0.00261865,
        0.00222127, 0.00409835, 0.00672984, 0.00495911, 0.00167125,
        0.00412307, 0.00376076, 0.00174988, 0.00165242, 0.00275903,
        0.00345436, 0.00432653, 0.0023644 , 0.00213329, 0.00269879,
        0.00410866, 0.00313236, 0.00328863, 0.00073543, 0.00339562,
        0.00083031, 0.00181394, 0.00115794, 0.00751617, 0.00173148,
        0.00163269, 0.00129218, 0.00308678, 0.00354371, 0.0037339 ,
        0.00285798, 0.00366017, 0.00209163, 0.00331607, 0.00476124,
        0.00564323, 0.00108011, 0.00286482, 0.00214294, 0.00352059,
        0.0014631 , 0.00128556, 0.00243886, 0.00107792, 0.00159495,
        0.00497325, 0.00223   , 0.0019621 , 0.00263505, 0.00352921,
        0.00653163, 0.00559425, 0.01410808, 0.00720963, 0.00290696,
        0.00507673, 0.00397257, 0.00011801, 0.00540743, 0.00481228,
        0.00582246, 0.00453934, 0.00620125, 0.00190749, 0.00396887,

In [ ]:
res = pd.DataFrame(grid_search_cv.cv_results_)

In [ ]:
res.sort_values(by='rank_test_score')

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__criterion,param_model__max_depth,param_model__min_samples_leaf,param_model__min_samples_split,param_model__splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
316,0.448780,0.018876,0.027518,0.001975,entropy,20,10,7,best,"{'model__criterion': 'entropy', 'model__max_de...",0.909028,0.916111,0.914028,0.915694,0.915972,0.914167,0.002676,1
318,0.359790,0.028460,0.030524,0.002537,entropy,20,10,10,best,"{'model__criterion': 'entropy', 'model__max_de...",0.909028,0.916111,0.914028,0.915694,0.915972,0.914167,0.002676,1
312,0.382793,0.021422,0.032313,0.002156,entropy,20,10,2,best,"{'model__criterion': 'entropy', 'model__max_de...",0.909028,0.916111,0.914028,0.915694,0.915972,0.914167,0.002676,1
314,0.377659,0.028532,0.042614,0.015778,entropy,20,10,5,best,"{'model__criterion': 'entropy', 'model__max_de...",0.909028,0.916111,0.914028,0.915694,0.915972,0.914167,0.002676,1
78,0.188288,0.015739,0.028380,0.002670,gini,5,10,10,best,"{'model__criterion': 'gini', 'model__max_depth...",0.909861,0.916667,0.908889,0.915556,0.915417,0.913278,0.003231,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,0.103728,0.004863,0.023601,0.004791,gini,5,7,10,random,"{'model__criterion': 'gini', 'model__max_depth...",0.873056,0.872222,0.871667,0.872500,0.872639,0.872417,0.000461,393
79,0.115671,0.010444,0.029227,0.001680,gini,5,10,10,random,"{'model__criterion': 'gini', 'model__max_depth...",0.873056,0.872222,0.871667,0.872500,0.872222,0.872333,0.000451,397
77,0.106520,0.012769,0.024564,0.002834,gini,5,10,7,random,"{'model__criterion': 'gini', 'model__max_depth...",0.873056,0.872222,0.871667,0.872500,0.872222,0.872333,0.000451,397
75,0.125084,0.015860,0.031362,0.004411,gini,5,10,5,random,"{'model__criterion': 'gini', 'model__max_depth...",0.873056,0.872222,0.871667,0.872500,0.872222,0.872333,0.000451,397
73,0.130863,0.008622,0.026449,0.003841,gini,5,10,2,random,"{'model__criterion': 'gini', 'model__max_depth...",0.873056,0.872222,0.871667,0.872500,0.872222,0.872333,0.000451,397

## marginal distance -->