In [ ]:
import pandas as pd
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

In [2]:
df=pd.read_csv('loan_data.csv')

In [3]:
df

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,male,Associate,47971.0,6,RENT,15000.0,MEDICAL,15.66,0.31,3.0,645,No,1
44996,37.0,female,Associate,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44997,33.0,male,Associate,56942.0,7,RENT,2771.0,DEBTCONSOLIDATION,10.02,0.05,10.0,668,No,1
44998,29.0,male,Bachelor,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1
44999,24.0,male,High School,51609.0,1,RENT,6665.0,DEBTCONSOLIDATION,17.05,0.13,3.0,628,No,1

In [4]:
x = df.drop(columns='loan_status')
y = df.loan_status

In [5]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, random_state=42, train_size=0.8)

In [6]:
# num_col = x.select_dtypes(include = 'number').columns
obj_col = x.select_dtypes(include = 'object').columns

In [7]:
x[obj_col].nunique()

person_gender                     2
person_education                  5
person_home_ownership             4
loan_intent                       6
previous_loan_defaults_on_file    2
dtype: int64

In [8]:
x['person_education'].unique()

array(['Master', 'High School', 'Bachelor', 'Associate', 'Doctorate'],
      dtype=object)

In [9]:
order = ['Master', 'High School', 'Bachelor', 'Associate', 'Doctorate']

In [10]:
preprocessing  = ColumnTransformer(
    transformers=[
        ('onehot_encodedr', OneHotEncoder(handle_unknown='ignore'), obj_col.drop('person_education')),
        ('orndinal_encoder', OrdinalEncoder(categories=[order], handle_unknown='use_encoded_value', unknown_value=-1), ['person_education'])

    ], remainder= 'passthrough'
)

main_pipeline = Pipeline(
    steps=[
        ('preprocessing', preprocessing),
        ('model', DecisionTreeClassifier(random_state=42))
    ]
)

grid_search_cv = GridSearchCV(
    estimator = main_pipeline,
    param_grid={
        'model__criterion' : ['gini', 'entropy'],           # if we are using any algorithm then there is no need to use that model name but if we are using pipeline then we have to use model name along with double underscore
        'model__max_depth' : [None, 5, 20, 50, 100],        # e.g., model__parameter
        'model__min_samples_split' : [2, 5, 7, 10],
        'model__min_samples_leaf' : [1, 3, 5, 7, 10],
        'model__splitter' : ['best', 'random']
    }, verbose = 10, n_jobs = -1
)

grid_search_cv.fit(xtrain, ytrain)

Fitting 5 folds for each of 400 candidates, totalling 2000 fits

GridSearchCV(estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('onehot_encodedr',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         Index(['person_gender', 'person_home_ownership', 'loan_intent',
       'previous_loan_defaults_on_file'],
      dtype='object')),
                                                                        ('orndinal_encoder',
                                                                         OrdinalEncoder(categories=[['Master',
                                                                                                     'High '
                                                                                                     'Scho...
                                                                                        handle_unknown='use_encoded_value',
                                                                                        unknown_value=-1),
                                                                         ['person_education'])])),
                                       ('model',
                                        DecisionTreeClassifier(random_state=42))]),
             n_jobs=-1,
             param_grid={'model__criterion': ['gini', 'entropy'],
                         'model__max_depth': [None, 5, 20, 50, 100],
                         'model__min_samples_leaf': [1, 3, 5, 7, 10],
                         'model__min_samples_split': [2, 5, 7, 10],
                         'model__splitter': ['best', 'random']},
             verbose=10)

In [11]:
grid_search_cv.best_estimator_

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehot_encodedr',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index(['person_gender', 'person_home_ownership', 'loan_intent',
       'previous_loan_defaults_on_file'],
      dtype='object')),
                                                 ('orndinal_encoder',
                                                  OrdinalEncoder(categories=[['Master',
                                                                              'High '
                                                                              'School',
                                                                              'Bachelor',
                                                                              'Associate',
                                                                              'Doctorate']],
                                                                 handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['person_education'])])),
                ('model',
                 DecisionTreeClassifier(criterion='entropy', max_depth=20,
                                        min_samples_leaf=10,
                                        random_state=42))])

In [12]:
grid_search_cv.best_params_

{'model__criterion': 'entropy',
 'model__max_depth': 20,
 'model__min_samples_leaf': 10,
 'model__min_samples_split': 2,
 'model__splitter': 'best'}

In [13]:
grid_search_cv.cv_results_

{'mean_fit_time': array([0.43770719, 0.20653162, 0.39206185, 0.16297479, 0.38290796,
        0.17159753, 0.38937311, 0.17455502, 0.36986427, 0.16326575,
        0.35496202, 0.15793848, 0.35963144, 0.16487384, 0.34770403,
        0.16133766, 0.34784365, 0.16077957, 0.35024128, 0.15286226,
        0.36815124, 0.21557393, 0.40298238, 0.17274637, 0.3545805 ,
        0.15996051, 0.41652722, 0.18996468, 0.33331871, 0.15188279,
        0.33014622, 0.16629949, 0.33700228, 0.14668021, 0.33834205,
        0.15195527, 0.3341094 , 0.15291691, 0.32222118, 0.15697594,
        0.1865715 , 0.11539116, 0.17422299, 0.11863413, 0.18312373,
        0.12724128, 0.18541799, 0.11434426, 0.2011878 , 0.13166237,
        0.18571849, 0.12612505, 0.18880916, 0.11562076, 0.18154216,
        0.12837396, 0.19479847, 0.12173333, 0.19730558, 0.12659664,
        0.20076485, 0.11280661, 0.18185468, 0.11754913, 0.20307703,
        0.1210948 , 0.18432913, 0.11736798, 0.18327589, 0.12708907,
        0.18292341, 0.1233798 , 0.18465858, 0.11892328, 0.19011512,
        0.12399936, 0.19494219, 0.11771331, 0.18374577, 0.11088028,
        0.35724654, 0.1621737 , 0.3527122 , 0.16687565, 0.36840639,
        0.16056223, 0.35628595, 0.17613583, 0.34361629, 0.1584434 ,
        0.32779236, 0.16240788, 0.35116906, 0.14275184, 0.35518579,
        0.15992041, 0.34366455, 0.15764165, 0.32936687, 0.1509264 ,
        0.32921605, 0.15875859, 0.33712463, 0.15721531, 0.31804729,
        0.16347375, 0.31605086, 0.14995804, 0.34037061, 0.13865252,
        0.32964287, 0.155755  , 0.31345344, 0.14708977, 0.30939708,
        0.15235572, 0.32011862, 0.15308781, 0.33861213, 0.14964552,
        0.36118755, 0.169068  , 0.3405899 , 0.17387395, 0.34382358,
        0.16177316, 0.36538262, 0.16232238, 0.33318076, 0.17175183,
        0.3509697 , 0.15836015, 0.34210119, 0.16413994, 0.34809194,
        0.16282158, 0.31944146, 0.15718307, 0.3242002 , 0.16207252,
        0.33501554, 0.14676781, 0.34711514, 0.15169611, 0.3505548 ,
        0.15151205, 0.31540074, 0.15668588, 0.3318048 , 0.14535222,
        0.32637391, 0.15206223, 0.32466798, 0.14947906, 0.31769471,
        0.15230293, 0.3295464 , 0.14522581, 0.31242318, 0.15206552,
        0.36724505, 0.1660862 , 0.35111547, 0.17903848, 0.3610312 ,
        0.16032763, 0.35881934, 0.16704698, 0.33697844, 0.17275615,
        0.33490038, 0.16544337, 0.3368454 , 0.15260849, 0.33536382,
        0.15139828, 0.34993515, 0.1607398 , 0.33417182, 0.15572515,
        0.33474593, 0.1663321 , 0.33917813, 0.16395078, 0.33925457,
        0.14537854, 0.32270865, 0.14875579, 0.32650094, 0.1508317 ,
        0.32718692, 0.14640312, 0.32317901, 0.1540648 , 0.31524005,
        0.16153769, 0.32480164, 0.14529405, 0.32275696, 0.14583697,
        0.40275426, 0.17629061, 0.41483655, 0.17373219, 0.41972857,
        0.18052735, 0.40643167, 0.16401567, 0.43411312, 0.16492352,
        0.39845195, 0.16570501, 0.39815035, 0.16529398, 0.38690257,
        0.1674746 , 0.38259816, 0.15700793, 0.37428646, 0.16041112,
        0.38231812, 0.16450391, 0.40123262, 0.16579809, 0.38624787,
        0.15284443, 0.40360003, 0.15508246, 0.37266941, 0.15774393,
        0.37964182, 0.15723057, 0.36918249, 0.14298387, 0.37030587,
        0.14957018, 0.36149664, 0.15119019, 0.36357012, 0.15583658,
        0.20888   , 0.12340384, 0.20236359, 0.1186831 , 0.19874191,
        0.11862283, 0.18835106, 0.1191134 , 0.1991827 , 0.11318274,
        0.20315065, 0.10702853, 0.20177021, 0.12781763, 0.18754535,
        0.11832147, 0.19748058, 0.12593818, 0.19395871, 0.11527057,
        0.20566707, 0.10973835, 0.20247808, 0.12015843, 0.20347323,
        0.09783292, 0.20139809, 0.11445069, 0.19869785, 0.12503114,
        0.19678121, 0.11257429, 0.20049667, 0.1091331 , 0.1979363 ,
        0.10515051, 0.21007957, 0.12599082, 0.21713572, 0.12167563,
        0.42191296, 0.17305188, 0.41030917, 0.17337909, 0.39319797,
        0.16263604, 0.44572005, 0.17931976, 0.44733109, 0.18470755,
        0.41440296, 0.16408029, 0.44741063, 0.20758233, 0.41170049,
        0.16183176, 0.4063858 , 0.14787555, 0.38281102, 0.15577168,
        0.37632384, 0.15429459, 0.47471395, 0.23139539, 0.5676156 ,
        0.26718497, 0.5018805 , 0.2411098 , 0.46270947, 0.26414456,
        0.56353183, 0.23758245, 0.54778271, 0.27141747, 0.43562551,
        0.17775726, 0.4532423 , 0.19419188, 0.43386612, 0.19340634,
        0.43419375, 0.18921018, 0.44277334, 0.16741724, 0.44182768,
        0.18042974, 0.44848027, 0.17481842, 0.43366475, 0.17400832,
        0.41044717, 0.16674128, 0.39194112, 0.17472768, 0.42904959,
        0.17617712, 0.40029502, 0.16261578, 0.39258022, 0.17165847,
        0.41297631, 0.1616437 , 0.4030879 , 0.15364404, 0.39038525,
        0.16223464, 0.37910614, 0.17463694, 0.3788949 , 0.16834989,
        0.40458121, 0.16712165, 0.39552875, 0.1533288 , 0.38742609,
        0.16818867, 0.37796049, 0.16423988, 0.39703889, 0.16073856,
        0.41871438, 0.18686647, 0.43506622, 0.16907048, 0.49341369,
        0.23188882, 0.45676742, 0.17038546, 0.48087559, 0.22076187,
        0.42467356, 0.16830316, 0.43526998, 0.17167778, 0.44077234,
        0.16289124, 0.42776179, 0.15731382, 0.43011332, 0.16347647,
        0.5381989 , 0.23353686, 0.51269412, 0.21562252, 0.48497419,
        0.28728251, 0.55442076, 0.20532198, 0.46004591, 0.15590057,
        0.38827109, 0.15590272, 0.38115878, 0.14969463, 0.39387379,
        0.15389304, 0.39496465, 0.1606523 , 0.35432439, 0.14348845]),
 'std_fit_time': array([0.01490752, 0.02489024, 0.02583371, 0.01216364, 0.01840903,
        0.01598039, 0.02470358, 0.01687202, 0.00965246, 0.01882629,
        0.00933336, 0.00714659, 0.01101239, 0.01269974, 0.02013508,
        0.0118605 , 0.01678791, 0.01106424, 0.00954615, 0.01333818,
        0.04256768, 0.04316324, 0.02444866, 0.00691348, 0.01506181,
        0.00815496, 0.02124432, 0.0170706 , 0.01326123, 0.00610197,
        0.01649395, 0.01518871, 0.01258663, 0.0065301 , 0.00933688,
        0.02079951, 0.01704457, 0.00724494, 0.01418522, 0.01478268,
        0.00754402, 0.00424802, 0.01438616, 0.00824552, 0.01690919,
        0.01366671, 0.0126788 , 0.0172821 , 0.01810167, 0.01362567,
        0.01224054, 0.00962648, 0.01083693, 0.01236638, 0.00615809,
        0.01133447, 0.01415825, 0.01196511, 0.01036686, 0.01642582,
        0.00412319, 0.00392141, 0.00844425, 0.01213272, 0.0143019 ,
        0.01229346, 0.01941437, 0.0069089 , 0.01458697, 0.01284779,
        0.01246726, 0.01401605, 0.01226332, 0.01399797, 0.01229118,
        0.00974769, 0.00881801, 0.00569086, 0.02355852, 0.0148352 ,
        0.01766406, 0.02198534, 0.02143093, 0.02038345, 0.01662322,
        0.01229194, 0.00937202, 0.00819669, 0.01482674, 0.01124681,
        0.0245248 , 0.02682239, 0.01731776, 0.00752056, 0.02231251,
        0.01646338, 0.01595216, 0.00509305, 0.01391151, 0.0111008 ,
        0.01271408, 0.00995876, 0.01143371, 0.01321024, 0.00906603,
        0.02134912, 0.02249174, 0.02230746, 0.00818706, 0.00970513,
        0.01480982, 0.01615133, 0.0138311 , 0.01227088, 0.0158211 ,
        0.01812163, 0.02804564, 0.01933151, 0.0116102 , 0.01931999,
        0.01863072, 0.00724143, 0.01902393, 0.0050584 , 0.02445168,
        0.01079273, 0.01591381, 0.01034868, 0.0245852 , 0.01244678,
        0.01699209, 0.0103609 , 0.01656144, 0.01653279, 0.01097241,
        0.01454524, 0.02184315, 0.01545885, 0.00729952, 0.01010285,
        0.01363254, 0.01606888, 0.01719952, 0.02232975, 0.00570242,
        0.01468163, 0.01801449, 0.01357556, 0.00480604, 0.01467345,
        0.01785857, 0.01824747, 0.02078594, 0.01567982, 0.01319483,
        0.01379551, 0.00843286, 0.01017329, 0.01111099, 0.0155262 ,
        0.01720179, 0.01999542, 0.02637848, 0.01840251, 0.01767909,
        0.00790478, 0.01814252, 0.01129049, 0.01920967, 0.0066085 ,
        0.01522931, 0.01368058, 0.01936129, 0.01594233, 0.01582443,
        0.01505552, 0.01734783, 0.02059738, 0.02689728, 0.01266881,
        0.01934994, 0.00802998, 0.01867637, 0.00555254, 0.01149797,
        0.00766773, 0.01062053, 0.01085525, 0.01708809, 0.01513203,
        0.01976448, 0.01633933, 0.01418575, 0.01704638, 0.02408596,
        0.02361252, 0.01466512, 0.01978787, 0.02044131, 0.0084807 ,
        0.02560071, 0.01708229, 0.01926841, 0.00699148, 0.01463858,
        0.0126739 , 0.00991847, 0.01231448, 0.01930457, 0.01695369,
        0.01752766, 0.00960864, 0.02523701, 0.01967867, 0.0216596 ,
        0.01198813, 0.0141469 , 0.01175418, 0.01360426, 0.01710539,
        0.01472551, 0.01212565, 0.01630066, 0.01130551, 0.01127861,
        0.01671675, 0.02359348, 0.0131876 , 0.02764592, 0.01634515,
        0.02002735, 0.00754977, 0.01322149, 0.01444889, 0.0116528 ,
        0.01904678, 0.00750243, 0.01791532, 0.01668653, 0.01009924,
        0.00822456, 0.01262515, 0.0138567 , 0.00473455, 0.00635355,
        0.01288665, 0.02117095, 0.01454149, 0.02040008, 0.01795221,
        0.01283248, 0.00978944, 0.01017547, 0.00763482, 0.01246842,
        0.01220581, 0.01994687, 0.01695666, 0.01197059, 0.00996843,
        0.01439958, 0.01006133, 0.00972164, 0.01038681, 0.00363801,
        0.01001163, 0.01879181, 0.01318189, 0.01297248, 0.01293822,
        0.00874725, 0.01439483, 0.01212128, 0.01334739, 0.00623632,
        0.01295069, 0.01191261, 0.01031854, 0.00786578, 0.01398305,
        0.03086115, 0.02757287, 0.02283263, 0.02050902, 0.02958425,
        0.02631399, 0.03971455, 0.03619767, 0.02827265, 0.01841313,
        0.04102825, 0.01243703, 0.01457292, 0.01982313, 0.01333457,
        0.00952968, 0.0147993 , 0.01151586, 0.01672879, 0.02124103,
        0.01383508, 0.00914499, 0.02801265, 0.09049851, 0.071843  ,
        0.09564171, 0.08645215, 0.04888842, 0.03777326, 0.03490191,
        0.13175611, 0.06547064, 0.04931439, 0.0412374 , 0.01544029,
        0.01462938, 0.05747533, 0.01891143, 0.01463922, 0.01804983,
        0.03053378, 0.01110467, 0.02768649, 0.0100258 , 0.00902881,
        0.01236509, 0.02639051, 0.01644113, 0.00744912, 0.01711112,
        0.01169606, 0.00781502, 0.0254163 , 0.01514196, 0.01894714,
        0.02166009, 0.01997876, 0.01409201, 0.01475565, 0.0085111 ,
        0.02161242, 0.01008287, 0.00937561, 0.00946813, 0.02159378,
        0.01399961, 0.0148851 , 0.01758041, 0.01944795, 0.00881828,
        0.01520407, 0.01536847, 0.01216055, 0.01776261, 0.02858598,
        0.02106504, 0.02136034, 0.01233184, 0.03437066, 0.00673801,
        0.02385804, 0.00882946, 0.01429693, 0.02276203, 0.01906279,
        0.02106464, 0.01900213, 0.02136878, 0.01895749, 0.03473877,
        0.02467795, 0.01033814, 0.0073068 , 0.01548193, 0.02088361,
        0.01595129, 0.01304391, 0.02094777, 0.02466936, 0.01981749,
        0.07820808, 0.01514606, 0.03164606, 0.02082491, 0.02413575,
        0.05836777, 0.06502548, 0.05134885, 0.02943475, 0.01223357,
        0.00588254, 0.01492551, 0.01975283, 0.01383247, 0.0119913 ,
        0.0137539 , 0.01341058, 0.01506843, 0.01665967, 0.01653551]),
 'mean_score_time': array([0.03347783, 0.02986426, 0.02989683, 0.03077679, 0.02928376,
        0.02973537, 0.03378663, 0.03060279, 0.03042989, 0.02837911,
        0.03114481, 0.02882338, 0.02874374, 0.02792058, 0.02886376,
        0.03005629, 0.03008184, 0.03534799, 0.02414846, 0.02896423,
        0.04008384, 0.04733214, 0.02907262, 0.03058734, 0.0391438 ,
        0.0335537 , 0.02908769, 0.0286068 , 0.02988601, 0.02835231,
        0.02731929, 0.03086076, 0.03194098, 0.02912321, 0.02981801,
        0.02742233, 0.02849493, 0.02848978, 0.02768507, 0.02964664,
        0.02485123, 0.02638273, 0.02939281, 0.02792168, 0.02855263,
        0.02707558, 0.02498202, 0.022861  , 0.0290925 , 0.02695813,
        0.02979426, 0.0252233 , 0.02959318, 0.0293786 , 0.02684226,
        0.02717924, 0.02911525, 0.02705517, 0.03139057, 0.02708154,
        0.0301805 , 0.03007178, 0.02793932, 0.02595453, 0.02749147,
        0.02778316, 0.02591248, 0.02848954, 0.03193059, 0.026752  ,
        0.02720523, 0.02566719, 0.03064265, 0.02207437, 0.02734652,
        0.02304373, 0.02811427, 0.02718577, 0.02689953, 0.02762208,
        0.02218843, 0.0276844 , 0.03323927, 0.03003373, 0.02887936,
        0.03297276, 0.02672062, 0.03374896, 0.02888107, 0.02705722,
        0.0291975 , 0.03172989, 0.02627888, 0.02672896, 0.02550855,
        0.03246441, 0.02859912, 0.03090682, 0.03026228, 0.03041587,
        0.02734914, 0.02641163, 0.0279686 , 0.02829881, 0.02452264,
        0.02704978, 0.0311625 , 0.03009915, 0.02776947, 0.0267786 ,
        0.02864199, 0.02985477, 0.03016691, 0.03205338, 0.02717729,
        0.02912202, 0.02952957, 0.02947717, 0.02605181, 0.02892709,
        0.02857046, 0.03110433, 0.02791772, 0.02946777, 0.02743297,
        0.02935538, 0.02933202, 0.02951431, 0.03063941, 0.03085804,
        0.02876902, 0.02776613, 0.03028193, 0.02788248, 0.02726889,
        0.03042235, 0.02918291, 0.02566352, 0.0245327 , 0.02745056,
        0.02656326, 0.02670889, 0.03217974, 0.03197875, 0.029004  ,
        0.02913942, 0.02680211, 0.02520676, 0.02961216, 0.03038559,
        0.02864289, 0.02770905, 0.02773986, 0.02763162, 0.0376236 ,
        0.02870617, 0.02866392, 0.02998767, 0.0271112 , 0.02825398,
        0.02819533, 0.03036599, 0.03554564, 0.03052793, 0.03038483,
        0.02772017, 0.02935753, 0.02996922, 0.02899423, 0.02724667,
        0.03147516, 0.02717447, 0.03066955, 0.03094401, 0.02843041,
        0.03071427, 0.02823248, 0.02579889, 0.02814412, 0.02956338,
        0.02709494, 0.02909446, 0.03314385, 0.02942791, 0.03216009,
        0.02924495, 0.02819586, 0.03206034, 0.02501388, 0.02807813,
        0.02741323, 0.03035617, 0.02740364, 0.03030047, 0.03189235,
        0.02986703, 0.02348557, 0.0264607 , 0.03264523, 0.03009133,
        0.02698674, 0.02773223, 0.03332009, 0.02810626, 0.02952433,
        0.02675452, 0.03187799, 0.02912145, 0.032832  , 0.03064055,
        0.02630472, 0.02930341, 0.02623277, 0.02731209, 0.03030515,
        0.02533412, 0.02812243, 0.02757597, 0.0251173 , 0.02924185,
        0.0260457 , 0.02586908, 0.02799468, 0.02804027, 0.02858791,
        0.02893887, 0.029951  , 0.03092337, 0.02881508, 0.02539415,
        0.02878861, 0.02437458, 0.02671976, 0.02435379, 0.02620115,
        0.02810249, 0.02721047, 0.02785101, 0.03045497, 0.02851772,
        0.0287787 , 0.02271714, 0.03161106, 0.03119445, 0.03120065,
        0.02622428, 0.03019776, 0.03050222, 0.02712283, 0.02570195,
        0.02959127, 0.02914629, 0.03091302, 0.02224474, 0.02681155,
        0.02658157, 0.02828498, 0.02724156, 0.02727304, 0.02746158,
        0.02566042, 0.02812471, 0.02839231, 0.02561135, 0.02953353,
        0.02596173, 0.02740421, 0.02828016, 0.03030734, 0.02597499,
        0.02566075, 0.02675562, 0.02922549, 0.02595739, 0.02994299,
        0.02601767, 0.02675238, 0.03076982, 0.02997289, 0.03038111,
        0.03076706, 0.02776899, 0.02896619, 0.02699823, 0.03542228,
        0.02823968, 0.0364923 , 0.0386858 , 0.02869315, 0.0285398 ,
        0.03413839, 0.03133912, 0.02635412, 0.0274406 , 0.02809258,
        0.02682853, 0.03091555, 0.02827911, 0.02874899, 0.02644877,
        0.03067741, 0.0294775 , 0.04063678, 0.03826509, 0.03306651,
        0.05031629, 0.03465385, 0.03717189, 0.03362675, 0.05489168,
        0.03443766, 0.04628658, 0.03278961, 0.03879304, 0.03334341,
        0.03404937, 0.03288078, 0.03043318, 0.03208551, 0.02801366,
        0.03040543, 0.02985826, 0.02988997, 0.03050094, 0.03170824,
        0.03249974, 0.03023   , 0.03100672, 0.03281927, 0.03094358,
        0.02486153, 0.03154945, 0.02442489, 0.02858562, 0.03343482,
        0.02849808, 0.02682786, 0.02878227, 0.03000517, 0.02890344,
        0.03054128, 0.02721658, 0.0295804 , 0.02984099, 0.02860389,
        0.03025584, 0.03119125, 0.02894034, 0.03130007, 0.03168941,
        0.03112397, 0.02687068, 0.02997108, 0.03194499, 0.03096662,
        0.03163018, 0.03043795, 0.02995663, 0.02692332, 0.03057485,
        0.02888112, 0.02886009, 0.03972831, 0.02781844, 0.02675672,
        0.02687826, 0.04032068, 0.02696438, 0.02947364, 0.03380313,
        0.03184061, 0.02661347, 0.02964292, 0.03183823, 0.03170829,
        0.02602282, 0.02987175, 0.02827044, 0.0367887 , 0.03821998,
        0.04412718, 0.03699818, 0.03386436, 0.04372678, 0.02984595,
        0.03818254, 0.03236308, 0.04272704, 0.02760577, 0.02724257,
        0.02778711, 0.0258996 , 0.03019605, 0.02758183, 0.02946396,
        0.02344255, 0.02935424, 0.02804155, 0.01355996, 0.01986489]),
 'std_score_time': array([0.00314284, 0.00546593, 0.00364247, 0.00381806, 0.00237465,
        0.00351246, 0.00312045, 0.01103569, 0.00100995, 0.00462344,
        0.00198764, 0.00277885, 0.00179073, 0.00335103, 0.00196563,
        0.00140634, 0.00145272, 0.01020835, 0.00589229, 0.00346886,
        0.01177893, 0.0212544 , 0.00060095, 0.00088367, 0.00819443,
        0.00838919, 0.00182579, 0.003023  , 0.00102086, 0.002178  ,
        0.00337305, 0.00140842, 0.00198134, 0.00391706, 0.00291612,
        0.00319228, 0.00195621, 0.00295561, 0.00541336, 0.0032933 ,
        0.00490964, 0.00353724, 0.00420482, 0.00507434, 0.00250352,
        0.0041043 , 0.00399989, 0.00237417, 0.00431085, 0.00475741,
        0.00329672, 0.00458593, 0.00421711, 0.00214955, 0.00526033,
        0.00211583, 0.00363557, 0.00432088, 0.0031352 , 0.00379739,
        0.00197466, 0.00222712, 0.00359074, 0.00221559, 0.00312063,
        0.00680676, 0.00317868, 0.00127935, 0.00246564, 0.00407903,
        0.00379937, 0.00594622, 0.00231031, 0.00164288, 0.0034179 ,
        0.00716293, 0.00487207, 0.00357995, 0.00468615, 0.00329678,
        0.00435176, 0.00157955, 0.00203063, 0.00145693, 0.00176342,
        0.00746936, 0.00611699, 0.00304158, 0.00210891, 0.00347413,
        0.00363001, 0.00260087, 0.00546886, 0.00341261, 0.00331659,
        0.0087397 , 0.00374017, 0.00248445, 0.00239084, 0.00174146,
        0.00255022, 0.00532199, 0.00301325, 0.00360785, 0.00332165,
        0.00398117, 0.00295199, 0.00178335, 0.00311468, 0.00265057,
        0.00233698, 0.00145082, 0.00386205, 0.00277696, 0.00177891,
        0.00258823, 0.00479893, 0.00485005, 0.0034188 , 0.00410794,
        0.00416453, 0.00377671, 0.00155676, 0.00189245, 0.00337244,
        0.00335176, 0.0017721 , 0.00430485, 0.00319852, 0.0047736 ,
        0.00227779, 0.00211542, 0.00340076, 0.00310629, 0.00124272,
        0.0012917 , 0.00297605, 0.00483747, 0.00429189, 0.00247101,
        0.00502034, 0.00302361, 0.00382061, 0.006835  , 0.00247186,
        0.00578236, 0.00357926, 0.00810815, 0.00243577, 0.00563877,
        0.0028467 , 0.00318158, 0.00222402, 0.00640005, 0.01770389,
        0.00092239, 0.00214878, 0.00385215, 0.00352766, 0.0045141 ,
        0.00453937, 0.00674424, 0.00536684, 0.00285328, 0.00679052,
        0.0036316 , 0.00287915, 0.00679661, 0.004267  , 0.00301096,
        0.00275287, 0.00298345, 0.00797617, 0.00280488, 0.00296884,
        0.00653979, 0.00239801, 0.00400028, 0.00383416, 0.00270947,
        0.00250173, 0.00173294, 0.0009048 , 0.00607043, 0.00319002,
        0.0042042 , 0.00298775, 0.00583811, 0.00592417, 0.00276777,
        0.00308687, 0.00312534, 0.00220657, 0.00614938, 0.00612334,
        0.00257909, 0.00535013, 0.00483613, 0.00598859, 0.00309524,
        0.00682879, 0.0031947 , 0.00276991, 0.00373622, 0.00190446,
        0.00480994, 0.00344203, 0.0044485 , 0.00731768, 0.00522475,
        0.00188015, 0.00362257, 0.00308261, 0.00318296, 0.00184571,
        0.00174241, 0.00254722, 0.00153784, 0.00226063, 0.00252046,
        0.00273736, 0.00267879, 0.0036922 , 0.00149718, 0.00149442,
        0.00301481, 0.00534479, 0.00588622, 0.00179602, 0.00368115,
        0.00244779, 0.00317022, 0.00322479, 0.00272108, 0.00340324,
        0.0057861 , 0.00358631, 0.00380395, 0.00499383, 0.00141352,
        0.00248882, 0.00493119, 0.00504488, 0.00208267, 0.00343421,
        0.00377107, 0.00346926, 0.0021703 , 0.00353009, 0.00394037,
        0.00120223, 0.00548885, 0.00736316, 0.00410787, 0.00274726,
        0.00243773, 0.00286213, 0.00479243, 0.00206639, 0.00390123,
        0.00463664, 0.00594478, 0.00436827, 0.00454469, 0.00534431,

In [14]:
res = pd.DataFrame(grid_search_cv.cv_results_)

In [15]:
res.sort_values(by='rank_test_score')

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__criterion,param_model__max_depth,param_model__min_samples_leaf,param_model__min_samples_split,param_model__splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
316,0.453242,0.057475,0.032881,0.005677,entropy,20,10,7,best,"{'model__criterion': 'entropy', 'model__max_de...",0.909028,0.916111,0.914028,0.915694,0.915972,0.914167,0.002676,1
318,0.433866,0.014639,0.032086,0.001250,entropy,20,10,10,best,"{'model__criterion': 'entropy', 'model__max_de...",0.909028,0.916111,0.914028,0.915694,0.915972,0.914167,0.002676,1
312,0.547783,0.049314,0.032790,0.003970,entropy,20,10,2,best,"{'model__criterion': 'entropy', 'model__max_de...",0.909028,0.916111,0.914028,0.915694,0.915972,0.914167,0.002676,1
314,0.435626,0.015440,0.033343,0.003248,entropy,20,10,5,best,"{'model__criterion': 'entropy', 'model__max_de...",0.909028,0.916111,0.914028,0.915694,0.915972,0.914167,0.002676,1
78,0.183746,0.023559,0.026900,0.004686,gini,5,10,10,best,"{'model__criterion': 'gini', 'model__max_depth...",0.909861,0.916667,0.908889,0.915556,0.915417,0.913278,0.003231,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,0.123380,0.014016,0.025667,0.005946,gini,5,7,10,random,"{'model__criterion': 'gini', 'model__max_depth...",0.873056,0.872222,0.871667,0.872500,0.872639,0.872417,0.000461,393
79,0.110880,0.014835,0.027622,0.003297,gini,5,10,10,random,"{'model__criterion': 'gini', 'model__max_depth...",0.873056,0.872222,0.871667,0.872500,0.872222,0.872333,0.000451,397
77,0.117713,0.005691,0.027186,0.003580,gini,5,10,7,random,"{'model__criterion': 'gini', 'model__max_depth...",0.873056,0.872222,0.871667,0.872500,0.872222,0.872333,0.000451,397
75,0.123999,0.009748,0.023044,0.007163,gini,5,10,5,random,"{'model__criterion': 'gini', 'model__max_depth...",0.873056,0.872222,0.871667,0.872500,0.872222,0.872333,0.000451,397
73,0.118923,0.013998,0.022074,0.001643,gini,5,10,2,random,"{'model__criterion': 'gini', 'model__max_depth...",0.873056,0.872222,0.871667,0.872500,0.872222,0.872333,0.000451,397