In [16]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [17]:
df = pd.read_csv('dataset_3.csv')
df

,amount,hour_of_day,account_age_days,recent_failures,foreign_txn,is_fraud
0,48.35,16,1968,0,0,0
1,40.89,19,1146,1,0,0
2,12.02,17,1531,2,0,0
3,110.56,17,2242,0,0,0
4,52.19,19,2987,1,0,0
...,...,...,...,...,...,...
3995,181.48,16,61,0,0,0
3996,69.92,1,2634,0,0,0
3997,34.81,15,2368,0,0,0
3998,22.88,9,2942,1,0,0
3999,55.63,0,2340,0,0,0

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   amount            4000 non-null   float64
 1   hour_of_day       4000 non-null   int64
 2   account_age_days  4000 non-null   int64
 3   recent_failures   4000 non-null   int64
 4   foreign_txn       4000 non-null   int64
 5   is_fraud          4000 non-null   int64
dtypes: float64(1), int64(5)
memory usage: 187.6 KB

In [30]:
df.describe()

,amount,hour_of_day,account_age_days,recent_failures,foreign_txn,is_fraud
count,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.00000
mean,126.573913,11.754000,1493.815750,0.321000,0.081250,0.00375
std,212.391523,6.835325,860.044656,0.564392,0.273253,0.06113
min,1.470000,0.000000,2.000000,0.000000,0.000000,0.00000
25%,32.365000,6.000000,746.000000,0.000000,0.000000,0.00000
50%,66.720000,12.000000,1484.500000,0.000000,0.000000,0.00000
75%,141.022500,18.000000,2235.250000,1.000000,0.000000,0.00000
max,4842.190000,23.000000,2997.000000,4.000000,1.000000,1.00000

In [19]:
x = df.drop(columns=['is_fraud'])
y = df['is_fraud']

In [20]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, random_state=42, train_size=0.8, stratify=y)

In [21]:
y.value_counts()

is_fraud
0    3985
1      15
Name: count, dtype: int64

In [22]:
scaler = StandardScaler()
scaler.fit_transform(xtrain)
scaler.transform(xtest)

array([[-0.35451631, -1.29018999, -1.61827205, -0.56530455, -0.29800288],
       [-0.53384213, -1.14378546, -1.16502688,  1.19611177, -0.29800288],
       [-0.11256527,  1.19868716, -0.0255056 ,  2.9575281 , -0.29800288],
       ...,
       [-0.11684018,  0.90587808, -1.70682381, -0.56530455, -0.29800288],
       [-0.28206321, -0.41176276, -1.57982195, -0.56530455, -0.29800288],
       [ 0.05790224, -1.58299907, -0.92383986, -0.56530455, -0.29800288]])

In [23]:
logisticModel = LogisticRegression(max_iter=1000, class_weight='balanced')

logisticModel.fit(xtrain, ytrain)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [24]:
y_pred = logisticModel.predict(xtest)

In [25]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, confusion_matrix

AccurayScore = accuracy_score(ytest, y_pred)
AccurayScore

0.90375

In [26]:
RecallScore = recall_score(ytest, y_pred)
RecallScore

0.6666666666666666

In [27]:
PrecisionScore = precision_score(ytest, y_pred)
PrecisionScore

0.02564102564102564

In [28]:
F1Score = f1_score(ytest, y_pred)
F1Score

0.04938271604938271

In [29]:
ConfusionMatrix = confusion_matrix(ytest, y_pred)
ConfusionMatrix

array([[721,  76],
       [  1,   2]], dtype=int64)